### PR TITLE
Updated OpenSSL to 1.1.1l

### PR DESCRIPTION
**Pull request by radarhere**
Python 3.10 requires OpenSSL 1.1.1 or newer - https://www.python.org/dev/peps/pep-0644/

### CODE REVIEW

**Comment by matthew-brett** [comment]
Thanks for this.

**Comment by radarhere** [comment]
Thanks - any ideas why https://hub.docker.com/r/matthewbrett/trusty/tags?page=1&ordering=last_updated reports that '32' was published by this change, but '64' hasn't been published in a year?

**Comment by matthew-brett** [comment]
I build and push the 32-bit one manually, and was leaving Dockerhub to do
the build and push for the 64-bit build.  It looks like that isn't
happening automatically any more.  Now I check, it looks like DockerHub has
disabled the automatic builds in the free tier.  I've just done a manual
push.  Does that help?

@rgommers - I don't suppose we have a Scipy team account for Dockerhub?  It
might be useful for these automated test images.  Perhaps not these ones,
as they are old now - but Mattip's Xenial versions.

**Comment by radarhere** [comment]
Yep, that helped! Thanks very much.

**Comment by rgommers** [comment]
We do have a SciPy team: https://hub.docker.com/orgs/scipy. It's on the free tier with max number of members, so I cannot easily add you.

There's also a NumPy team: https://hub.docker.com/orgs/numpy/repositories. I can add you to that? This doesn't seem SciPy-specific.

**Comment by matthew-brett** [comment]
> There's also a NumPy team: https://hub.docker.com/orgs/numpy/repositories. I can add you to that? This doesn't seem SciPy-specific.

I was hoping that we had some above-free-tier credits in terms of
number of downloads (here for many CI runs) and automated building
from Github push.  Do we have anything like that?

**Comment by rgommers** [comment]
No we don't have anything like that for Docker images. The anaconda wheels bucket is the only thing with above-free-level storage and bandwidth.

**Pull request merged**
