### PR TITLE
Fix install locations of 32-bit python

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
This was broken with https://github.com/matthew-brett/trusty/commit/fbc2bbe7ffd5037c9a99e72ff3c4ef6a97ea826c and was noticed today because of yesterday's push to dockerhub.

**Comment by matthew-brett** [comment]
Oops, thanks.

**Comment by isuruf** [comment]
@matthew-brett, can you please upload a new version of the 32-bit image to dockerhub?

**Comment by matthew-brett** [comment]
Just building now.

**Comment by isuruf** [comment]
Thanks

**Comment by matthew-brett** [comment]
Uploaded now - is OK?

**Comment by isuruf** [comment]
Yes. Thanks

**Pull request merged**
