### PR TITLE
update pythons

### PR DESCRIPTION
**Pull request by mattip**
Update the pythons

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Pandas has some issues with a test on Python 3.7.0 that is fixed in later versions of Python. Is this PR required to get newer versions of 3.7 in multibuild?

**Comment by matthew-brett** [comment]
@mattip - where are we with this one?  At first blush it looks like this should be a PR against the 32 bit branch ....

**Comment by mattip** [comment]
It seems I targeted the wrong branch.

**Comment by mattip** [comment]
@TomAugspurger do you need 32 bit or 64 bit for pandas?

**Comment by TomAugspurger** [comment]
64

**Comment by matthew-brett** [comment]
OK - I'll apply these few lines, get back to you when done.

**Comment by matthew-brett** [comment]
I think this is done now - can either of you check?   I've uploaded the 32-bit build; the 64-bit build gets uploaded to Dockerhub directly.

**Comment by mattip** [comment]
Closing, this was done differently.

**Comment by TomAugspurger** [comment]
Thanks!

**Pull request closed without merging**
